package com.theguy.app.enums;

public enum FinancialAction {
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    ESCROW_FUNDED,
    ESCROW_RELEASED,
    PROVIDER_CREDITED,
    PROVIDER_DEBITED,
    PLATFORM_FEE_COLLECTED,
    TAX_RECORDED,
    PAYOUT_REQUESTED,
    PAYOUT_APPROVED,
    PAYOUT_COMPLETED,
    PAYOUT_FAILED,
    PAYOUT_REVERSED,
    DISPUTE_OPENED,
    DISPUTE_RESOLVED,
    DISPUTE_REJECTED,
    REFUND_PROCESSED
}
