ALTER TABLE services ADD COLUMN IF NOT EXISTS min_price NUMERIC(10,2);
ALTER TABLE services ADD COLUMN IF NOT EXISTS max_price NUMERIC(10,2);
ALTER TABLE services ADD COLUMN IF NOT EXISTS adjustment_percent INTEGER DEFAULT 10;
